@startuml

'Diagramme de séquence (PlantUML)'

'Configuration charte graphique'
hide footbox
skinparam sequenceParticipantBackgroundColor White
skinparam sequenceActorBackgroundColor White

'Déclaration des acteurs et des participants (déjà existants avant la séquence)'
actor "__Membre__" as member
participant "__m:MiniSocs__" as m
participant "__rs:Reseau__" as rs
participant "__me:Membre__" as me
participant "__u:Utilisateur__" as u

'Séquence avec les messages, les créations de participants, etc.'
member -> m ++ : posterMessage(pseudoM, rs, mess)

opt mess respecte RCF822 ∧ non vide
  m -> m ++ : e1=existenceReseau(rs)
  opt e1 != null
    m -> rs ++ : e2=existenceMembre(pseudoM, rs)
    opt e2 == True
      rs -> me ++ : pseudoU=pseudoUtilisateur(pseudoM)
      me -> me ++ : mod=estModerateur(pseudoU)
      me -> u ++ : b1=estBloque(pseudoU)
      u --> me ++ : b1
      opt b1 == False
        create "<<new>>\n__mes:Message__" as mess
        me -> "__mes:Message__" as mess ++ : mess=<<create(mess)>>
        opt mod == True
          mess -> mess ++ : rendreVisible(mess)
	end
    end
  end    
end
end
@enduml
