@startuml

'Diagramme de séquence (PlantUML)'

'Configuration charte graphique'
hide footbox
skinparam sequenceParticipantBackgroundColor White
skinparam sequenceActorBackgroundColor White

'Déclaration des acteurs et des participants (déjà existants avant la séquence)'
actor "__Utilisateur__" as user
participant "__m:MiniSocs__" as m
participant "__rs:Reseau__" as rs
participant "__me:Membre__" as me
participant "__u:Utilisateur__" as u

'Séquence avec les messages, les créations de participants, etc.'
user -> m ++ : posterMessage(pseudoM, nomRs, mess)
opt pseudoM, rs, mess non null ∧ non vide
  m -> m ++ : rs=rechercheReseau(rs)
  opt rs != null
    m -> rs ++ : posterMessage(pseudoM,mess)
    rs -> rs++ : me=rechercheMembre(pseudoM)
    opt me != null 
    	rs->me++ : u=rechercheUtilisateur(pseudoM)
    	me -> me ++ : mod=estModerateur()
    	me->u++ : b=estBloque()
    	return
    	opt b == False
        	create "<<new>>\n__mes:Message__" as mess
        	me -> "__mes:Message__" as mess ++ : mess=<<create(mess)>>
        opt mod == True
          mess -> mess ++ : rendreVisible()
      	   
end
@enduml
